import os
import datetime
import re
import uuid
import asyncio
from core.config import PROJECT_VAULT_PATH, OBSIDIAN_INBOX_PATH
from core.processors import generate_content_with_fallback
from core.utils import chunk_text

async def run_weekly_synthesis(manual: bool = False) -> dict:
    try:
        now = datetime.datetime.now()
        seven_days_ago = now - datetime.timedelta(days=7)
        
        # 1. Scan for Markdown files in the vault (excluding raw/ or synthesis/ folders or files starting with '_')
        notes_to_synthesize = []
        
        if not os.path.exists(PROJECT_VAULT_PATH):
            return {"status": "error", "message": "Vault path does not exist"}
            
        for root, dirs, files in os.walk(PROJECT_VAULT_PATH):
            # Skip special directories
            if "raw" in root or "synthesis" in root:
                continue
            for file in files:
                if file.endswith(".md") and not file.startswith("_"):
                    filepath = os.path.join(root, file)
                    try:
                        mtime = datetime.datetime.fromtimestamp(os.path.getmtime(filepath))
                        if mtime >= seven_days_ago:
                            with open(filepath, "r", encoding="utf-8", errors="ignore") as f:
                                content = f.read()
                            notes_to_synthesize.append({
                                "title": file.replace(".md", ""),
                                "content": content
                            })
                    except Exception as e:
                        print(f"Error reading {file} for synthesis: {e}")
                        
        if not notes_to_synthesize:
            return {"status": "success", "message": "No new notes in the last 7 days to synthesize."}
            
        # 2. Build the context for LLM prompt
        notes_context = ""
        for i, note in enumerate(notes_to_synthesize):
            summary_match = re.search(r'> \*\*AI Summary:\*\* (.*)', note["content"])
            summary_str = summary_match.group(1) if summary_match else note["content"][:300]
            notes_context += f"\nNote {i+1}: {note['title']}\nSummary/Snippet: {summary_str}\n"
            
        date_str = now.strftime("%Y-%m-%d")
        week_num = now.isocalendar()[1]
        year = now.year
        
        prompt = f"""
You are the expert AI Librarian of the Second Brain. Synthesize the learnings and updates from the last 7 days.

Here are the notes created/modified this week:
{notes_context}

Please generate a comprehensive, structured weekly synthesis document in Markdown. The document MUST follow this format exactly:

# WEEKLY INTELLECTUAL DIGEST: {date_str} (Week {week_num}, {year})

## 🧠 Core Themes Explored
- **[Theme 1 Title]**: [Brief summary of why this theme was explored, linking back to the notes using wiki links e.g. [[Note Title]]]
- **[Theme 2 Title]**: [Brief summary, linking back using [[Note Title]]]

## 💡 Key Synthesized Insights
- [Describe the combined insights generated by connecting multiple notes. Be creative and show how different concepts relate to one another.]

## 📌 Action Items & Next Steps
- [ ] [Extracted action item or next research area based on this week's notes]

Format your output nicely with clean Markdown. Do not include markdown JSON structures or raw JSON wrapper, just output raw Markdown.
"""
        response, model_used = generate_content_with_fallback(prompt, purpose="weekly_synthesis")
        synthesis_content = response.text.strip()
        
        # Add YAML frontmatter
        full_markdown = f"""---
type: synthesis
date: {date_str}
week: {week_num}
year: {year}
ai_model: {model_used}
tags: ["#weekly-digest", "#synthesis"]
---
{synthesis_content}
"""
        
        # 3. Save to PROJECT_VAULT_PATH/synthesis/
        synthesis_filename = f"Weekly-Digest-{date_str}.md"
        
        proj_synth_dir = os.path.join(PROJECT_VAULT_PATH, "synthesis")
        obsidian_synth_dir = os.path.join(OBSIDIAN_INBOX_PATH, "synthesis")
        
        os.makedirs(proj_synth_dir, exist_ok=True)
        os.makedirs(obsidian_synth_dir, exist_ok=True)
        
        proj_synth_path = os.path.join(proj_synth_dir, synthesis_filename)
        obsidian_synth_path = os.path.join(obsidian_synth_dir, synthesis_filename)
        
        with open(proj_synth_path, "w", encoding="utf-8") as f:
            f.write(full_markdown)
        with open(obsidian_synth_path, "w", encoding="utf-8") as f:
            f.write(full_markdown)
            
        # 4. Index the summary inside ChromaDB vector store
        try:
            from core.db import get_vault_collection
            vault_collection = get_vault_collection()
            relative_filename = os.path.join("synthesis", synthesis_filename).replace("\\", "/")
            new_url = f"local://{relative_filename}"
            
            try:
                vault_collection.delete(where={"filename": relative_filename})
            except:
                pass
                
            chunks = [chunk for chunk in chunk_text(synthesis_content) if chunk.strip()]
            if chunks:
                vault_collection.add(
                    documents=chunks,
                    metadatas=[{"filename": relative_filename, "url": new_url, "content_hash": ""} for _ in chunks],
                    ids=[f"synthesis_{uuid.uuid4().hex}_chunk_{i}" for i in range(len(chunks))]
                )
        except Exception as ex:
            print(f"Error indexing weekly summary in ChromaDB: {ex}")
            
        return {
            "status": "success",
            "message": f"Weekly digest generated successfully: {synthesis_filename}",
            "filename": synthesis_filename,
            "note_count": len(notes_to_synthesize)
        }
        
    except Exception as e:
        print(f"Weekly synthesis loop failed: {e}")
        return {"status": "error", "message": str(e)}
