# The path to the podhelper.rb file
require File.expand_path(File.join(File.dirname(__FILE__), 'Flutter', 'podhelper.rb'))

# Uncomment this line to define a global platform for your project
platform :ios, '14.0'

# CocoaPods analytics sends usage stats. In order to automate CI/CD you may want to disable it
# env['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_install_all_ios_pods(cocoapods_targets_obj)
  setup_line = File.expand_path(File.join(File.dirname(__FILE__), '..', '.flutter-plugins-dependencies'))
  if File.exist?(setup_line)
    eval(File.read(setup_line), binding, setup_line)
  else
    puts "Warning: Flutter dependencies file not found"
  end
  # Install helper to install plugins
  flutter_install_ios_plugin_pods(cocoapods_targets_obj)
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods(super_binder = nil)
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
